### ISSUE TITLE
Auth using http requests

### ISSUE THREAD

**Issue by twisted89** [wohali/ips4-oauth2-server#12]
Not so much an issue but a query - Is it possible to login and authenticate using just HTTP requests?
I'd like to avoid bundling a browser with a desktop app (it bloats the size significantly) just to display the login page. It would be much more convenient to just provide a native form with username/password and handle it manually in code. 

Thanks.

**Comment by wohali** [comment]
As stated in the README file, the OAuth workflow doesn't require a browser. You do, however, have to be logged in first...which you can fake.

You should be able to do a POST to http(s)://your-ips4-site.com/login with the following fields:

- auth: [username]
- password: [password]
- login__standard_submitted: 1 (may be optional, not sure)

The response header should include values for _ips4_member_id_ and _ips4_pass_hash_. Set these in a cookie in all of your subsequent requests by setting a request header in the form "Cookie: ips4_member_id=###; ips4_pass_hash=############"

Good luck!

**Comment by twisted89** [comment]
Thanks but just tried this and it gives the error
"The page you requested does not exist
Error code: 2S100/6"

Something to do with URL rewriting/friendly URL's being enabled?

**Comment by wohali** [comment]
Comment updated with revised login POST details. See if that works for you.

**Comment by twisted89** [comment]
Afraid no luck either, 307 Temporary Redirect to /login/?cookieCheck=1.

Attempting to post with cookieCheck set returns 403 forbidden. 

I've attempted to talk to Invision Support about this and as usual lame excuse 'We only provide support for usage and configuration, not technical support' even though it's literally called 'Technical Support'....

Edit:
On closer inspection the redirect does set ips4_IPSSessionFront but I'm not sure what we can use this for.

**Comment by wohali** [comment]
I'm sorry, you're going to have to experiment on your own to make this work. My recommendation is to use the developer console in Firefox or Chrome, flush all caches, turn on network monitoring in the dev console, and log yourself in. You should be able to replicate the precise sequence required to login by doing this.
