### ISSUE TITLE
No redirect after login

### ISSUE THREAD

**Issue by aer127** [wohali/ips4-oauth2-server#13]
I'm seeing the same issue as was reported in Issue #2 

I get redirected to the login page successfully. But after logging in, the browser does not redirect back to my redirect URL. Is there any information I can provide that would help debug the issue?

**Comment by aer127** [comment]
@wohali  Here's the ref section you requested from #2

ref=aHR0cDovL3d3dy5kcnVtY29ycHNwbGFuZXQuY29tL2ZvcnVtcy9hcHBsaWNhdGlvbnMvb2F1dGgyc2VydmVyL2ludGVyZmFjZS9vYXV0aC9hdXRob3JpemUucGhwP2NsaWVudF9pZD04ODA3YWQyMTQwZTRiMzkwYmM3MSZyZWRpcmVjdF91cmk9bXlhcHBzY2hlbWUlM0ElMkYlMkZyZXNwb25zZSZzdGF0ZT1LN080SDJCTiZyZXNwb25zZV90eXBlPWNvZGU=

**Comment by aer127** [comment]
@wohali 
One more piece of info. After successfully logging in, I get taking to the main forums listing for my site. This is the URL
http://www.mysite.com/forums/?_fromLogin=1

**Comment by aer127** [comment]
@wohali 
Another piece of info, the URL for the login page that includes the ref prm gets a 301 (permanently moved) response from the server and then navigates to the login url minus the ref prm. This seems to be the root of the issue. Not sure what could be causing this. This may be related to HTTPS, specifically if the base url for a site is http while the login page is https, which is the case for my site. Authorize.php gets the base url from IPS settings, but the base url is http which when used for the login page gets returned a 301 and redirected to the https login page.

**Comment by aer127** [comment]
This was in fact related to the site being served over http and login over https. After changing both to be served over http, everything works. I will close this issue.

**Comment by wohali** [comment]
Glad to hear it - sorry I didn't respond sooner, been a busy January.
