### ISSUE TITLE
Unsupported scope when app login for first time

### ISSUE THREAD

**Issue by arthurdapaz** [wohali/ips4-oauth2-server#16]
Hello! I'm facing a strange problem.

Well, I have enabled all scopes at **Admin Panel** / _Community_ / **OAuth2 Server** / _Applications_ / **MyCustomApplication**

But, my redirect URL is coming back like this:

error=**invalid_scope**&error_description=**An+unsupported+scope+was+requested**&state=yhhbmhykiyjujijobkaxoyimemyytromoetfqtumawjfjsgcynagnimqjdtramhp

This happens only after sign in on my app for the first time, if I close and reopen the app (that will do the authentication process again), since the login is successful, it will work flawless.

What's going on? Any tips?

**Comment by wohali** [comment]
I am aware of this issue but busy with other contracts and some personal issues at the moment. I will get back to you next week.

**Comment by wohali** [comment]
Found the bug. Working on a fix.

**Comment by wohali** [comment]
Fixed in 1.3.0. This was an RFC3986 compliance issue.
