### ISSUE TITLE
Avatar not retrieved and used by Rocket.Chat

### ISSUE THREAD

**Issue by JohnnyKing94** [wohali/ips4-oauth2-server#17]
Just an info, why rocket.chat doesn't use the avatar of IPS?
Is the avatar not a data retrieved by rocket.chat?

**Comment by wohali** [comment]
Correct. Rocket.Chat would need to be modified. It's not a bug of my project. We provide the avatar in the user.profile scope, and Django can use it.

https://github.com/wohali/ips4-oauth2-server/blob/8519c97f5a17d820c42c6cefdc0e8bde646ce639/interface/oauth/me.php#L42-L49
