### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ApertureDevelopment** [wohali/ips4-oauth2-server#19]
Hello,

Is there a way that I can return an information if the account is verified? Like, in our forum Users need to be approved by an Staff member, how can I return if the user has been approved?

**Comment by wohali** [comment]
Generally the best way to handle this is to have the new users who are approved moved into a different user group, then set permissions on the OAuth Server to only allow users in that group (+ admins + whomever else) access to the application you've configured. Does that make sense?

**Comment by ApertureDevelopment** [comment]
So you are saying me, there is a permission node so that you are allowed to log in with the OAuth application, and we should grant authenticated users access to it, in order to prevent  non authed users to Log in? 
So Basicly: Lets say I am registering an account with false E-Mail address and not approved by an Administrator, but I still am able to log in with my Account to the OAuth application ? Is there nothing that gets returned that says "Ey dis user is not fully validated" ?

**Comment by wohali** [comment]
There is a permission node for each OAuth Application you define that says which user groups can use the application.

So:
1. Admin creates an OAuth Application and only grants permission to users in the Members User Group, not to Newbies User Group. (see screenshot below) Path: ACP > Community > OAuth2 Server > Applications > (your application) > Permissions (lock icon)
1. You register an account with fake email address. IPS puts the user in the "Newbies" IPS User Group (not fully promoted to Members yet - this is done by your Administrators).
1. You try to connect to OAuth application, are redirected to enter your IPS username and password.
1. You receive a **Permission Denied** error and are **not** logged into the OAuth application. (No special reason is given, just permission denied.)

Screenshot of permission configuration:
![mwsnap 2017-09-12 14_30_32](https://user-images.githubusercontent.com/112292/30342263-3c7b8124-97c7-11e7-9c40-52bf781b7ce8.png)

**Comment by ApertureDevelopment** [comment]
Another small question, is it possible to return the group to my application? I kinda need it for what I am doing ^^'

**Comment by wohali** [comment]
Yes! Request the `user.groups` scope and you'll get the list of groups in which they are a member.
