### ISSUE TITLE
Wrong urls

### ISSUE THREAD

**Issue by JohnnyKing94** [wohali/ips4-oauth2-server#5]
I tried to setup today the Rocket.Chat app, but i found out this error in your app. It seems you report a wrong url in the parameter list... in fact it's missing the **oauth** word... instead on your documentation, it's correct... just look the images to understand

How it looks like on ips4 app
![app-ips](https://dl.dropboxusercontent.com/u/89718989/Screenshot/Github/ips4-oauth2-server/bandicam%202016-09-03%2013-12-44-315.jpg)

How you report in the doc
![app-doc](https://dl.dropboxusercontent.com/u/89718989/Screenshot/Github/ips4-oauth2-server/bandicam%202016-09-03%2013-13-09-836.jpg)

Clearly it's missing that **oauth** part after **interface** word... can you fix it?

**Comment by wohali** [comment]
Already fixed, see https://github.com/wohali/ips4-oauth2-server/commit/e83d372d8fc90eacee3b1fd331bf9acfe67d62ae

**Comment by wohali** [comment]
For reference this should be fixed in the latest 1.2.4 release available on the Invision Power marketplace as well as in the releases section from here.
