### ISSUE TITLE
Missing theme template

### ISSUE THREAD

**Issue by JohnnyKing94** [wohali/ips4-oauth2-server#6]
When we give the consent to authorize the Rocket.Chat app for the account, i see this page rendered in a wrong way... like it's not loading any themes or templates... i don't know if it is done on purpose, but i'd like to have our proper theme rendered for this page

![authorization-page](https://dl.dropboxusercontent.com/u/89718989/Screenshot/Github/ips4-oauth2-server/bandicam%202016-09-03%2013-11-01-380.jpg)

**Comment by wohali** [comment]
It's intentional. Rendering within the theme is something we can consider for the future but is a non-trivial change given how the integration is written.

**Comment by JohnnyKing94** [comment]
By the way, everything is localizable in that page, except for Yes and No, if i change the values, the new registrations won't be allowed, only logins... i thought it has to do with the code...

**Comment by wohali** [comment]
Correct, that's a known limitation. I'll open a new issue on this as an enhancement, but don't expect a fix anytime soon.

**Comment by wohali** [comment]
Fixed in 1.3.0.
